- VaultName: your-vault-name
  ResourceGroupName: your-resource-group-name
  SubscriptionId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
  Location: northcentralus
  TenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
  AccessPolicies:
  - Type: User
    DisplayName: first-last
    Alias: alias@provider.com
    PermissionsToKeys: []
    PermissionsToSecrets:
    - Get
    - List
    PermissionsToCertificates: []
  - Type: User
    DisplayName: first-last
    Alias: alias@provider.com
    PermissionsToKeys:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToSecrets:
    - Get
    - List
    - Set
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToCertificates:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    - ManageContacts
    - ManageIssuers
    - GetIssuers
    - ListIssuers
    - SetIssuers
    - DeleteIssuers
  ResourceGroupName: almiliTest
  SubscriptionId: 7d3b156b-1072-4060-97f6-42057dc19952
  Location: northcentralus
  TenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
  AccessPolicies:
  - Type: User
    DisplayName: Aleksandar Milicevic
    Alias: almili@microsoft.com
    PermissionsToKeys:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToSecrets:
    - Get
    - List
    - Set
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToCertificates:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    - ManageContacts
    - ManageIssuers
    - GetIssuers
    - ListIssuers
    - SetIssuers
    - DeleteIssuers
  - Type: Service Principal
    DisplayName: almili-Test1-7d3b156b-1072-4060-97f6-42057dc19952
    Alias: ''
    PermissionsToKeys: []
    PermissionsToSecrets:
    - Get
    - List
    PermissionsToCertificates: []

    - DeleteIssuers
    - Purge
  - Type: User
    DisplayName: Mazin Shaaeldin
    Alias: t-mashaa@microsoft.com
    PermissionsToKeys:
    - Get
    - List
    PermissionsToSecrets:
    - Get
    - List
    PermissionsToCertificates:
    - Get
    - List
  ResourceGroupName: RBACTest
  SubscriptionId: 6b94a915-57a9-4023-8fe8-3792e113ddff
  Location: eastus
  TenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47
  AccessPolicies:
  - Type: User
    DisplayName: Josh Becker
    Alias: jobecker@microsoft.com
    PermissionsToKeys:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToSecrets:
    - Get
    - List
    - Set
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToCertificates:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    - ManageContacts
    - ManageIssuers
    - GetIssuers
    - ListIssuers
    - SetIssuers
    - DeleteIssuers
  - Type: User
    DisplayName: Mazin Shaaeldin
    Alias: t-mashaa@microsoft.com
    PermissionsToKeys: []
    PermissionsToSecrets:
    - Get
    - List
    - Set
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToCertificates:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    - ManageContacts
    - ManageIssuers
    - GetIssuers
    - ListIssuers
    - SetIssuers
    - DeleteIssuers
  - Type: User
    DisplayName: Katie Helman
    Alias: t-kahelm@microsoft.com
    PermissionsToKeys:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToSecrets:
    - Get
    - List
    - Set
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToCertificates:
    - Get
    - List
  - Type: User
    DisplayName: Soumya Mishra
    Alias: somish@microsoft.com
    PermissionsToKeys:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToSecrets:
    - Get
    - List
    - Set
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToCertificates:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    - ManageContacts
    - ManageIssuers
    - GetIssuers
    - ListIssuers
    - SetIssuers
    - DeleteIssuers
  - Type: Service Principal
    DisplayName: RBACAutomationApp
    Alias: ''
    PermissionsToKeys:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToSecrets:
    - Get
    - List
    - Set
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToCertificates:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    - ManageContacts
    - ManageIssuers
    - GetIssuers
    - ListIssuers
    - SetIssuers
    - DeleteIssuers
  - Type: User
    DisplayName: Opeyemi Olaoluwa
    Alias: t-opolao@microsoft.com
    PermissionsToKeys:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToSecrets:
    - Get
    - List
    - Set
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToCertificates:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    - ManageContacts
    - ManageIssuers
    - GetIssuers
    - ListIssuers
    - SetIssuers
    - DeleteIssuers
- VaultName: your-vault-name
  ResourceGroupName: your-resource-group-name
  SubscriptionId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
  Location: eastus
  TenantId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
  AccessPolicies:
  - Type: Group
    DisplayName: group-name
    Alias: alias@service.microsoft.com
    PermissionsToKeys:
    - Get
    - List
    PermissionsToSecrets:
    - Backup
    PermissionsToCertificates:
    - ManageContacts
  - Type: User
    DisplayName: first-last
    Alias: alias@provider.com
    PermissionsToKeys: []
    PermissionsToSecrets:
    - Get
    - List
    - Set
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToCertificates:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
  - Type: User
    DisplayName: first-last
    Alias: alias@provider.com
    PermissionsToKeys:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToSecrets:
    - Get
    - List
    - Set
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToCertificates: []
  - Type: Service Principal
    DisplayName: app-name
    Alias: ''
    PermissionsToKeys:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToSecrets:
    - Get
    - List
    - Set
    - Delete
    - Recover
    - Backup
    - Restore
    PermissionsToCertificates:
    - Get
    - List
    - Update
    - Create
    - Import
    - Delete
    - Recover
    - Backup
    - Restore
    - ManageContacts
    - ManageIssuers
